# pylint: skip-file
# Generated by Django 3.2.25 on 2026-03-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='lists_manager.vocabulary'),
        ),
    ]
