# pylint: skip-file
# Generated by Django 3.2.25 on 2026-03-10 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_manager', '0002_alter_list_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
